### ISSUE TITLE
loading Gcode 

### ISSUE THREAD

**Issue by VeridisQuo555** [NicHub/stewart-platform-esp32#3]
I was just wonder what your method of loading gcode

**Comment by NicHub** [comment]
Currently, the program accepts G-code sent one command after another via the serial port. To send these commands, you can use any software that communicates over the serial port. In this project, I’ve chosen to write a Python script that reads a text file containing the G-code instructions and sends them one by one to the platform.

To use it, you need to upload the project on the ESP with this setting in platformio.ini: `ENABLE_SERIAL_READ=true`.

Then on your computer, open a terminal, go to the gcode2serial directory and execute the Python program that sends the G-code commands to the platform. You’ll need to change <SERIAL PORT> with the ESP32 serial port, i.e. something like COMx, where x is a number.

```
cd <gcode2serial>
py gcode2serial.py -p <SERIAL PORT> -f demo_123.gcode
```

**Comment by VeridisQuo555** [comment]
if i write an entire program would that work or do i have to send one line at a time

**Comment by NicHub** [comment]
If you want to operate the platform in real time from a computer, you have to send the command in G-code format one by one.

But you can also hardcode the commands in the ESP. There are some examples in `Hexapod_Demo.cpp`:

- `demoMov_circles`
- `demoMov_shakeHeave`
- `demoMov_MinMaxAllAxis`

**Comment by VeridisQuo555** [comment]
i see i will get back to you if get it to work

**Comment by NicHub** [comment]
@VeridisQuo555, you might be interested in this issue :

https://github.com/NicHub/stewart-platform-esp32/issues/4
